confAuthorization:
  confLimit: 10
confConnectionInfo:
  connectDatabase: testDB
  connectHost: 127.0.0.1
  connectPassword: ''
  connectPort: 5432
  connectUser: stepan
confFailPathToCategoryNews: ./data/categoryNewsTest.json
confLogger:
  preconfFilePath: ./logging/logTest
  preconfMinLevel: Debug
confNews:
  confMaxLimit: 10

